# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remote_controle_bot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(386, 439)
        MainWindow.setMinimumSize(QtCore.QSize(386, 0))
        MainWindow.setMaximumSize(QtCore.QSize(386, 16777215))
        MainWindow.setStyleSheet("MainWindow {\n"
"    background-color: transparent;\n"
"    background-color: transparent;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(386, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(386, 16777215))
        self.centralwidget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(14, 22, 33);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_top_bar = QtWidgets.QFrame(self.centralwidget)
        self.frame_top_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_top_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_top_bar.setStyleSheet("")
        self.frame_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_bar.setObjectName("frame_top_bar")
        self.btn_users = QtWidgets.QPushButton(self.frame_top_bar)
        self.btn_users.setGeometry(QtCore.QRect(0, -5, 135, 30))
        self.btn_users.setMinimumSize(QtCore.QSize(135, 30))
        self.btn_users.setMaximumSize(QtCore.QSize(135, 30))
        self.btn_users.setStyleSheet("QPushButton{\n"
"font: 12pt \"Segoe UI Black\";\n"
"background-color: rgb(9, 114, 194);\n"
"color: rgb(240, 240, 240);\n"
"border-radius: 5px;}")
        self.btn_users.setObjectName("btn_users")
        self.btn_bot_settings = QtWidgets.QPushButton(self.frame_top_bar)
        self.btn_bot_settings.setGeometry(QtCore.QRect(145, -5, 105, 30))
        self.btn_bot_settings.setMinimumSize(QtCore.QSize(105, 30))
        self.btn_bot_settings.setMaximumSize(QtCore.QSize(105, 16777215))
        self.btn_bot_settings.setStyleSheet("QPushButton{\n"
"font: 12pt \"Segoe UI Black\";\n"
"background-color: rgb(143, 143, 143);\n"
"color: rgb(240, 240, 240);\n"
"border-radius: 5px;}\n"
"QPushButton:hover{\n"
"font: 13pt \"Segoe UI Black\";\n"
"background-color: rgb(11, 153, 255);}\n"
"QPushButton:focus:pressed{\n"
"font: 12pt \"Segoe UI Black\";\n}")
        self.btn_bot_settings.setObjectName("btn_bot_settings")
        self.btn_close_window = QtWidgets.QPushButton(self.frame_top_bar)
        self.btn_close_window.setGeometry(QtCore.QRect(365, 5, 16, 16))
        self.btn_close_window.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close_window.setMaximumSize(QtCore.QSize(16, 16))
        self.btn_close_window.setStyleSheet("QPushButton{\n"
"background: #f64a32;\n"
"border-radius: 8px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(185, 55, 37);\n}")
        self.btn_close_window.setText("")
        self.btn_close_window.setObjectName("btn_close_window")
        self.gridLayout.addWidget(self.frame_top_bar, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_users = QtWidgets.QWidget()
        self.page_users.setObjectName("page_users")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_users)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.page_users)
        self.scrollArea.setStyleSheet("*{background-color: transparent;}\n"
"QScrollBar:vertical{\n"
"     background-color: rgb(54, 57, 59);\n"
"     margin-bottom: 5px;\n"
"     margin-top: 5px;\n"
"     margin-right: 2px;\n"
"     width: 12px;\n"
"     border-radius: 5px;}\n"
"QScrollBar::handle:vertical{\n"
"     background-color: rgb(37, 82, 165);\n"
"     min-height: 5px;\n"
"     border-radius: 7px;}\n"
"QScrollBar::sub-line:vertical{\n"
"     height: 0px;\n"
"     width: 0px;}\n"
"QScrollBar::add-line:vertical{\n"
"     height: 0px;\n"
"     width: 0px;}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"     background: none;}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 386, 394))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.stackedWidget.addWidget(self.page_users)
        self.page_bot_setings = QtWidgets.QWidget()
        self.page_bot_setings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_bot_setings.setObjectName("page_bot_setings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_bot_setings)
        self.verticalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.page_bot_setings)
        self.frame.setMinimumSize(QtCore.QSize(364, 100))
        self.frame.setMaximumSize(QtCore.QSize(364, 100))
        self.frame.setStyleSheet("background-color: rgb(37, 46, 61);\n"
"border-radius: 8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_2.setStyleSheet("background-color: rgb(93, 112, 224);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(0, 26))
        self.label.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label.setStyleSheet("padding-left:8px;\n"
"color: rgb(240, 240, 240);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_bf_link = QtWidgets.QPushButton(self.frame_2)
        self.btn_bf_link.setMinimumSize(QtCore.QSize(75, 25))
        self.btn_bf_link.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_bf_link.setStyleSheet("QPushButton{\n"
"font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 65, 72);\n"
"color: rgb(240, 240, 240);\n"
"border: solid;\n"
"border-width: 2px;\n"
"border-color: rgb(29, 27, 27);\n"
"border-radius: 10px;}\n"
"QPushButton:hover{\n"
"background-color: rgb(97, 117, 129);\n"
"border-width: 3px;}\n")
        self.btn_bf_link.setObjectName("btn_bf_link")
        self.horizontalLayout_2.addWidget(self.btn_bf_link)
        self.btn_save = QtWidgets.QPushButton(self.frame_2)
        self.btn_save.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_save.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_save.setStyleSheet("QPushButton{\n"
"background-color: rgb(93, 112, 224);\n"
"color: rgb(240, 240, 240);\n"
"padding-left: 10px;\n"
"padding-right: 10px;}\n"
"QPushButton:hover{background-color: rgb(120, 140, 255);}")
        self.btn_save.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("my ui/assets/baton_picturie/save_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon)
        self.btn_save.setIconSize(QtCore.QSize(20, 20))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(360, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(360, 30))
        self.lineEdit_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 65, 72);\n"
"color: rgb(240, 240, 240);\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"margin-left: 4px;\n"
"border: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(29, 27, 27);\n"
"border-radius: 15px;")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(32767)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_8 = QtWidgets.QFrame(self.page_bot_setings)
        self.frame_8.setMinimumSize(QtCore.QSize(364, 81))
        self.frame_8.setMaximumSize(QtCore.QSize(364, 81))
        self.frame_8.setStyleSheet("background-color: rgb(37, 46, 61);\n"
"border-radius: 8px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label_2.setStyleSheet("color: rgb(240, 240, 240);\n"
"background-color: rgb(93, 112, 224);\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox.setMinimumSize(QtCore.QSize(220, 30))
        self.checkBox.setMaximumSize(QtCore.QSize(220, 30))
        self.checkBox.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 65, 72);\n"
"color: rgb(240, 240, 240);\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"margin-left: 4px;\n"
"border: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(29, 27, 27);\n"
"border-radius: 10px;")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.verticalLayout_4.addWidget(self.frame_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.page_bot_setings)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_users.setText(_translate("MainWindow", "Пользователи"))
        self.btn_bot_settings.setText(_translate("MainWindow", "Настройки"))
        self.label.setText(_translate("MainWindow", "Токен бота"))
        self.btn_bf_link.setText(_translate("MainWindow", "get token"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Token from bot father"))
        self.label_2.setText(_translate("MainWindow", "Настройки Windows"))
        self.checkBox.setText(_translate("MainWindow", "Запускать при старте системы"))
